Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-066784287e358dad1  # Corrected from 'ImageID' to 'ImageId'
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my, inst, from, cloudformation ]]
      SecurityGroups:
        - !Ref VprofileSG
  VprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 183.32.39.124/32
           